// <auto-generated />
namespace BlogSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201805311358183_UserFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
